// Hunting grounds. Each preset encodes where mispricing lives in that category.
// categoryIds are left empty on purpose — resolve exact IDs with the built-in
// taxonomy lookup and pin them here once verified (IDs occasionally shift).

export const PRESETS = [
  {
    id: 'lenses',
    label: 'Camera Lenses',
    blurb: 'Best asymmetry-to-liquidity ratio on eBay. Sellers list "old Canon lens" without knowing FD L glass from a kit lens.',
    queries: ['canon fd 50mm 1.2', 'takumar 50mm 1.4', 'nikkor ai-s 105mm', 'minolta rokkor 58mm', 'olympus zuiko 100mm f2'],
    typoBrands: ['takumar', 'voigtlander', 'summicron', 'nikkor', 'rokkor'],
    conditionIds: [],
    auctionOnly: true,
    fixable: false,
    expectModelNumbers: true,
    shipEstimate: 12,
    maxPrice: 400,
  },
  {
    id: 'vintage-computing',
    label: 'Vintage Computing',
    blurb: 'Estate sellers have no idea. Model M keyboards, HP calculators, retro Apple.',
    queries: ['ibm model m keyboard', 'hp 15c calculator', 'hp 41cx', 'apple macintosh se', 'commodore 64 lot'],
    typoBrands: ['commodore', 'macintosh', 'northgate'],
    conditionIds: [],
    auctionOnly: true,
    fixable: true,
    expectModelNumbers: true,
    shipEstimate: 25,
    maxPrice: 500,
  },
  {
    id: 'hifi-parts',
    label: 'Hi-Fi · For Parts',
    blurb: '"Won\'t power on" on vintage Marantz/Sansui is often a fuse or recap. Sellers can\'t test, so they price at scrap.',
    queries: ['marantz receiver', 'sansui receiver', 'pioneer sx receiver', 'technics turntable', 'mcintosh amplifier'],
    typoBrands: ['marantz', 'sansui', 'mcintosh', 'technics'],
    conditionIds: ['7000', '3000'],
    auctionOnly: true,
    fixable: true,
    expectModelNumbers: true,
    shipEstimate: 45,
    maxPrice: 600,
  },
  {
    id: 'test-equipment',
    label: 'Test Equipment',
    blurb: 'Engineer estates. Tektronix/Keysight scopes with huge knowledge asymmetry. Slower resale velocity — price that in.',
    queries: ['tektronix oscilloscope', 'keysight signal generator', 'fluke multimeter lot', 'hp agilent analyzer'],
    typoBrands: ['tektronix', 'keysight', 'agilent'],
    conditionIds: [],
    auctionOnly: true,
    fixable: true,
    expectModelNumbers: true,
    shipEstimate: 40,
    maxPrice: 800,
  },
  {
    id: 'retro-gaming',
    label: 'Retro Gaming · Repair',
    blurb: 'HDMI port and stick-drift fixes. Trade bench time for margin. Skip anything activation-locked.',
    queries: ['nintendo switch for parts', 'ps5 hdmi for parts', 'gamecube console lot', 'game boy advance sp'],
    typoBrands: ['nintendo', 'gamecube'],
    conditionIds: ['7000'],
    auctionOnly: false,
    fixable: true,
    expectModelNumbers: false,
    shipEstimate: 15,
    maxPrice: 250,
  },
  {
    id: 'open-hunt',
    label: 'Open Hunt',
    blurb: 'The wider net: pro tools, dead mechanical watches, retired sealed LEGO.',
    queries: ['snap on tool lot', 'mechanical watch not running lot', 'lego sealed retired set', 'vintage estate electronics lot'],
    typoBrands: ['milwaukee', 'seamaster'],
    conditionIds: [],
    auctionOnly: true,
    fixable: true,
    expectModelNumbers: false,
    shipEstimate: 20,
    maxPrice: 500,
  },
]
